### ISSUE TITLE
failed to connect to host

### ISSUE THREAD

**Issue by Foxardo** [JoeJoeTV/AstroTuxLauncher#3] opened 2023-12-24 12:47 UTC
i try to join with no whitelist enabled but it says it failed to connect
nomater whether the server has a password or not

on the linux side it sayes the network connectshon is fine please help

**Comment by JoeJoeTV** [comment] 2023-12-24 21:51
What does the [server check tool](https://servercheck.spycibot.com) say about your server?
Also, are you connecting from the same network as the server is on or the same machine?

**Comment by Foxardo** [comment] 2023-12-24 22:34
same network both on etho. ill test the server real quick when i get it up

**Comment by Foxardo** [comment] 2023-12-24 22:40
ok on launch i just found by default no encryption in on. i'm not sure if thats the issue
results for server check tool Status: Online
Server:
Reachable
Playfab:
Registered
Server Version:
1.29.61.0
Type:
Self-Hosted
Players:
0/8
Password:
false

**Comment by JoeJoeTV** [comment] 2023-12-24 22:41
Can you send me the output that AstroTuxLauncher produces?

**Comment by Foxardo** [comment] 2023-12-24 22:42
is that a log from the server or the console output

**Comment by JoeJoeTV** [comment] 2023-12-24 22:42
You can just send the most recent log file

**Comment by Foxardo** [comment] 2023-12-24 22:46
[12:40:21] [Launcher/INFO] Working directory: /home/kali/AstroTuxLauncher
[12:40:21] [DedicatedServer/INFO] NOTICE: Encryption is disabled. All players that want to join the Dedicated Server have to disable encryption on their clients too
[12:40:22] [Launcher/INFO] No update available, the Astroneer Dedicated Server is on the newest version
[12:40:24] [Launcher/INFO] Checking Network Configuration...
[12:40:26] [Launcher/INFO] Network configuration looks good
[12:40:36] [Launcher/INFO] RCON network configuration looks good
[12:40:36] [DedicatedServer/INFO] Preparing to start the Dedicated Server...
[12:40:37] [DedicatedServer/INFO] Started Dedicated Server process (v1.29.61.0). Waiting for registration...
[12:41:12] [DedicatedServer/INFO] Dedicated Server ready! Took 34.19 seconds to register
[12:41:12] [Notify/INFO] Server started!
[12:41:12] [Launcher/INFO] Enter 'help' to get help about command usage
[12:56:05] [Notify/INFO] Game saved!
[13:11:02] [Notify/INFO] Game saved!
[13:26:04] [Notify/INFO] Game saved!
[13:41:02] [Notify/INFO] Game saved!
[13:56:04] [Notify/INFO] Game saved!
[14:11:07] [Notify/INFO] Game saved!
[14:26:04] [Notify/INFO] Game saved!
[14:41:07] [Notify/INFO] Game saved!
[14:56:04] [Notify/INFO] Game saved!
[15:11:06] [Notify/INFO] Game saved!
[15:26:08] [Notify/INFO] Game saved!
[15:41:10] [Notify/INFO] Game saved!
[15:56:08] [Notify/INFO] Game saved!
[16:11:10] [Notify/INFO] Game saved!
[16:26:08] [Notify/INFO] Game saved!
[22:22:56] [Launcher/WARNING] Unknown command: invalid choice: 'players' (choose from 'help', 'shutdown', 'restart', 'info', 'kick', 'whitelist', 'list', 'savegame', 'player')
[22:23:01] [Command/INFO] Online Players (0):
[22:23:16] [Command/INFO] Information about the Dedicated Server:
[22:23:16] [Command/INFO]     - Build: 1.29.61.0
[22:23:16] [Command/INFO]     - Server URL: 210.50.142.225:7767
[22:23:16] [Command/INFO]     - Owner: BooGuy
[22:23:16] [Command/INFO]     - Has Password: no
[22:23:16] [Command/INFO]     - Whitelist: disabled
[22:23:16] [Command/INFO]     - Creative Mode: no
[22:23:16] [Command/INFO]     - Save Game: SAVE_1
[22:23:16] [Command/INFO]     - Players: 0/8
[22:23:16] [Command/INFO]     - Average FPS: 3.0020954608917236
[22:24:13] [Launcher/WARNING] Unknown command: invalid choice: 'log' (choose from 'help', 'shutdown', 'restart', 'info', 'kick', 'whitelist', 'list', 'savegame', 'player')
[22:24:35] [keyboard-input-thread/ERROR] Error in input thread run:

**Comment by JoeJoeTV** [comment] 2023-12-24 22:49
Have you disabled encryption on your client?

**Comment by Foxardo** [comment] 2023-12-24 22:56
no i will try that now

**Comment by JoeJoeTV** [comment] 2023-12-24 22:58
As AstroTuxLauncher mentions when starting, currently to run it on Linux, encryption has to be disabled on the server and all clients that want to connect to the server.

**Comment by Foxardo** [comment] 2023-12-24 23:02
how do i turn encryption off in client side. also sorry for wasting you time on today

**Comment by JoeJoeTV** [comment] 2023-12-24 23:06
Is your client running on Windows or Linux (via Proton)?

**Comment by Foxardo** [comment] 2023-12-24 23:07
windows

**Comment by Foxardo** [comment] 2023-12-24 23:08
for client

**Comment by JoeJoeTV** [comment] 2023-12-24 23:09
For windows, press Win+R and type `"%UserProfile%/AppData/Local/Astro/Saved/Config/WindowsNoEditor/Engine.ini"` and add at the end of the file with the file editor of your choice:
```ini
[SystemSettings]

net.AllowEncryption=False
```

**Comment by Foxardo** [comment] 2023-12-24 23:15
thank you so much have a good day

**Comment by JoeJoeTV** [comment] 2023-12-24 23:15
Did that fix the problem entirely?

**Comment by JoeJoeTV** [comment] 2023-12-28 19:46
I'm just assuming that the issue is now resolved and I can close this

**Closed by JoeJoeTV** 2023-12-28 19:46 UTC
